import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const css = await readFile(resolve(root, 'src/styles/global.css'), 'utf8');
const html = `<!doctype html>
<html lang="en">
<head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" /><title>CivicAI Portal Prototype</title><style>${css}</style></head>
<body>
<main class="app-shell">
  <section class="hero" aria-labelledby="portal-title"><div><p class="eyebrow">Mock mode · No production Chatbase connection</p><h1 id="portal-title">CivicAI Portal</h1><p>A safe prototype for reviewing a municipal tourism chat UI, visitor quick actions, structured request metadata, and future Chatbase-related backend/API integration points.</p></div><div class="status-card"><span class="status-dot" aria-hidden="true"></span>Placeholder API layer active</div></section>
  <section class="quick-actions" aria-label="Quick actions" id="quick-actions"></section>
  <div class="portal-grid"><section class="panel chat-panel" aria-labelledby="chat-heading"><div class="panel-header"><div><p class="eyebrow">Conversation</p><h2 id="chat-heading">Ask a visitor question</h2></div><button class="ghost-button" type="button" id="simulate-error">Simulate error</button></div><div class="conversation" aria-live="polite" id="conversation"></div><form class="chat-input" id="chat-form"><label for="message-input">Message</label><div><input id="message-input" type="text" placeholder="Ask about highlights, transit, food, events, or visitor routes…" /><button type="submit">Send</button></div></form></section>
  <aside class="side-column"><section class="panel" aria-labelledby="form-heading"><p class="eyebrow">Visitor context</p><h2 id="form-heading">Request metadata preview</h2><form class="request-form" id="request-form"><label>Visitor name<input name="name" placeholder="Alex Visitor" /></label><label>Email<input name="email" placeholder="alex@example.test" /></label><label>Area or hotel district<input name="neighborhood" placeholder="Central district" /></label><label>Request type<select name="requestType"><option>Trip planning question</option><option>Cultural route</option><option>Transport question</option><option>Food recommendation</option><option>Event question</option></select></label><label>Details<textarea name="details" placeholder="Describe the visitor need…"></textarea></label><button type="submit">Preview metadata</button></form></section><section class="panel" aria-labelledby="metadata-heading"><p class="eyebrow">Future integration boundary</p><h2 id="metadata-heading">Action/API placeholder</h2><p class="action-result" id="action-result">No action/API placeholder has been triggered yet.</p><pre id="metadata-preview"></pre></section></aside></div>
</main>
<script type="module">
const defaultMetadata = { topic: 'general', department: 'Visitor Services', urgency: 'normal', channel: 'web-prototype', locale: 'en-US' };
const quickActions = [
  { id: 'culture', label: 'Cultural highlights', prompt: 'Suggest cultural highlights for a first-time visitor who has two hours downtown.', description: 'Preview museums, heritage sites, public art, and walking routes.', metadata: { topic: 'culture', department: 'Visitor Services', urgency: 'low', channel: 'web-prototype', locale: 'en-US' } },
  { id: 'transport', label: 'Public transport info', prompt: 'How can visitors get from the central station to the waterfront without a car?', description: 'Demo transit, walking, accessibility, and visitor mobility guidance.', metadata: { topic: 'transport', department: 'Mobility Desk', urgency: 'normal', channel: 'web-prototype', locale: 'en-US' } },
  { id: 'food', label: 'Local food guide', prompt: 'Recommend local food areas for visitors who want casual lunch options.', description: 'Preview neighborhood food suggestions and visitor-friendly filtering.', metadata: { topic: 'food', department: 'Tourism Office', urgency: 'low', channel: 'web-prototype', locale: 'en-US' } },
  { id: 'events', label: 'Events calendar', prompt: 'Show me visitor-friendly events happening this weekend.', description: 'Demo municipal event discovery and calendar-style guidance.', metadata: { topic: 'events', department: 'Events Desk', urgency: 'low', channel: 'web-prototype', locale: 'en-US' } }
];
const state = { messages: [{ role: 'assistant', content: 'Welcome to the CivicAI Portal municipal tourism demo. Ask about cultural highlights, public transport, local food, or visitor events. Responses are mocked for safe review.', timestamp: timestamp(), metadata: defaultMetadata }], isLoading: false, error: null, metadata: defaultMetadata };
const conversation = document.querySelector('#conversation');
const metadataPreview = document.querySelector('#metadata-preview');
const actionResult = document.querySelector('#action-result');
function timestamp() { return new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }); }
function escapeHtml(value) { return value.replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[char]); }
function render() { const hasUserMessages = state.messages.some((message) => message.role === 'user'); conversation.innerHTML = ''; if (!hasUserMessages) conversation.insertAdjacentHTML('beforeend', '<div class="empty-state">Start with a message or choose a quick action card.</div>'); for (const message of state.messages) conversation.insertAdjacentHTML('beforeend', '<article class="message ' + message.role + '"><div class="message-meta"><span>' + message.role + '</span><time>' + message.timestamp + '</time></div><p>' + escapeHtml(message.content) + '</p></article>'); if (state.isLoading) conversation.insertAdjacentHTML('beforeend', '<div class="loading-state">Loading placeholder assistant response…</div>'); if (state.error) conversation.insertAdjacentHTML('beforeend', '<div class="error-state">' + escapeHtml(state.error) + '</div>'); metadataPreview.textContent = JSON.stringify(state.metadata, null, 2); }
function submitMessage(text, metadata = state.metadata) { const trimmed = text.trim(); if (!trimmed || state.isLoading) return; state.error = null; state.metadata = metadata; state.messages.push({ role: 'user', content: trimmed, timestamp: timestamp(), metadata }); state.isLoading = true; render(); window.setTimeout(() => { /* Future Chatbase-related backend/API integration point: replace this mock timeout with a server-side API request. Keep production secrets off the client. */ state.messages.push({ role: 'assistant', content: 'Mock tourism response: I would route “' + trimmed + '” to ' + metadata.department + ' for visitor guidance. In a future Chatbase integration, this can become a real assistant response with localized references.', timestamp: timestamp(), metadata }); actionResult.textContent = 'Placeholder action ready: ' + metadata.department + ' / ' + metadata.topic + ' / ' + metadata.urgency; state.isLoading = false; render(); }, 650); }
document.querySelector('#quick-actions').innerHTML = quickActions.map((action) => '<button class="quick-action" type="button" data-action="' + action.id + '"><strong>' + action.label + '</strong><span>' + action.description + '</span></button>').join('');
document.querySelector('#quick-actions').addEventListener('click', (event) => { const button = event.target.closest('button[data-action]'); if (!button) return; const action = quickActions.find((item) => item.id === button.dataset.action); submitMessage(action.prompt, action.metadata); });
document.querySelector('#chat-form').addEventListener('submit', (event) => { event.preventDefault(); const input = document.querySelector('#message-input'); submitMessage(input.value); input.value = ''; });
document.querySelector('#simulate-error').addEventListener('click', () => { state.isLoading = false; state.error = 'Simulated error: the placeholder tourism information API did not respond. No real API call was made.'; render(); });
document.querySelector('#request-form').addEventListener('submit', (event) => { event.preventDefault(); const data = new FormData(event.currentTarget); const requestTypeMap = { 'Trip planning question': { topic: 'general', department: 'Visitor Services' }, 'Cultural route': { topic: 'culture', department: 'Visitor Services' }, 'Transport question': { topic: 'transport', department: 'Mobility Desk' }, 'Food recommendation': { topic: 'food', department: 'Tourism Office' }, 'Event question': { topic: 'events', department: 'Events Desk' } }; const selectedRequest = requestTypeMap[data.get('requestType')] || requestTypeMap['Trip planning question']; state.metadata = { topic: selectedRequest.topic, department: selectedRequest.department, urgency: 'normal', channel: 'web-prototype', locale: 'en-US' }; actionResult.textContent = 'Structured visitor context preview for ' + (data.get('name') || 'anonymous visitor') + ' in ' + (data.get('neighborhood') || 'an unspecified area') + '. This remains mock-only.'; state.messages.push({ role: 'system', content: 'Structured visitor context captured: ' + data.get('requestType') + '. Details are shown as metadata only and are not sent to production services.', timestamp: timestamp(), metadata: state.metadata }); render(); });
render();
</script>
</body></html>`;
await mkdir(resolve(root, 'dist'), { recursive: true });
await writeFile(resolve(root, 'dist/index.html'), html);
console.log('Built CivicAI Portal prototype to dist/index.html');
